// SQL Projects from Dune Analytics
export const sqlProjects = [
  {
    title: "THX Network Analysis",
    description: "Comprehensive analysis of THX Network's token distribution and user engagement metrics.",
    image: "/blockchain-growth-dashboard.png",
    link: "https://dune.com/queries/3851503",
    client: "THX Network",
    tags: ["Token Distribution", "User Engagement", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "OLAS Token Distribution",
    description: "Detailed analysis of OLAS token distribution patterns and holder demographics.",
    image: "/token-distribution-dashboard.png",
    link: "https://dune.com/cryptall/olas-token-distribution",
    client: "OLAS Network",
    tags: ["Token Distribution", "Holder Analysis", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "GU Trade Analysis",
    description: "Trading patterns and market analysis for GU Factory's digital assets.",
    image: "/financial-market-overview.png",
    link: "https://dune.com/cryptall/gu-trade",
    client: "GU Factory",
    tags: ["Trading Analysis", "Market Metrics", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "LSTache Performance Tracking",
    description: "Performance analysis and metrics tracking for LSTache protocol.",
    image: "/performance-dashboard-lines.png",
    link: "https://dune.com/queries/4340943",
    client: "LSTache",
    tags: ["Performance Metrics", "Protocol Analysis", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "Agents.fun Analytics",
    description: "User engagement and platform metrics for the Agents.fun platform.",
    image: "/user-engagement-heatmap-dashboard.png",
    link: "https://dune.com/cryptall/agentsdotfun",
    client: "Agents.fun",
    tags: ["User Engagement", "Platform Metrics", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "AG Sniper Bot Analysis",
    description: "Performance tracking and strategy analysis for AG Sniper Bot.",
    image: "/bot-performance-overview.png",
    link: "https://dune.com/ag_bot/ag-sniper-bot",
    client: "AG Sniper Bot",
    tags: ["Bot Performance", "Strategy Analysis", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "EVM Token Analyzer",
    description: "Comprehensive token analysis tool for EVM-compatible blockchains.",
    image: "/crypto-token-dashboard.png",
    link: "https://dune.com/my_copilot_bae/evm-token-analyzer",
    client: "Copilot BAE",
    tags: ["Token Analysis", "EVM", "Multi-chain", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "LSD Investment Opportunities",
    description: "Research on the best Liquid Staking Derivative investment opportunities on Ethereum.",
    image: "/investment-dashboard-comparison.png",
    link: "https://dune.com/cryptall/market-opportunities-research",
    client: "Independent Research",
    tags: ["LSD", "Investment Research", "Ethereum", "Dune Analytics"],
    category: "sql",
  },
  {
    title: "Sei DeFi Ecosystem Analysis",
    description: "Comprehensive analysis of the DeFi ecosystem on the Sei blockchain.",
    image: "/sei-defi-dashboard.png",
    link: "https://flipsidecrypto.xyz/cryptall/sei-defi-world-ShOoiL",
    client: "Independent Research",
    tags: ["Sei", "DeFi", "Ecosystem Analysis", "Flipside Crypto"],
    category: "sql",
  },
  {
    title: "NEAR Protocol Staking Analysis",
    description: "In-depth analysis of staking patterns and validator performance on the NEAR Protocol.",
    image: "/near-staking-dashboard.png",
    link: "https://flipsidecrypto.xyz/cryptall/staking-on-near-protocol-Cg2v0h",
    client: "Independent Research",
    tags: ["NEAR Protocol", "Staking", "Validator Analysis", "Flipside Crypto"],
    category: "sql",
  },
  {
    title: "Thorchain RUNE Analysis",
    description: "Detailed analysis of RUNE token metrics, liquidity pools, and trading patterns on Thorchain.",
    image: "/thorchain-rune-analysis.png",
    link: "https://flipsidecrypto.xyz/cryptall/analyzing-rune-IYdmTX",
    client: "Independent Research",
    tags: ["Thorchain", "RUNE", "Token Analysis", "Flipside Crypto"],
    category: "sql",
  },
  {
    title: "Burrow Finance on NEAR Protocol",
    description: "Performance analysis and user behavior study of Burrow Finance on the NEAR Protocol.",
    image: "/burrow-finance-dashboard.png",
    link: "https://flipsidecrypto.xyz/cryptall/burrow-finance-on-near-protocol-ntDZLj",
    client: "Independent Research",
    tags: ["NEAR Protocol", "Burrow Finance", "DeFi", "Lending", "Flipside Crypto"],
    category: "sql",
  },
]

// Python Projects from Kaggle
export const pythonProjects = [
  {
    title: "Whales Market Fees: ETH vs SOL",
    description: "Comparative analysis of transaction fees for whale addresses on Ethereum and Solana networks.",
    image: "/eth-sol-fees-comparison.png",
    link: "https://www.kaggle.com/code/omojoallwell/comparison-of-whales-market-fees-on-eth-and-sol",
    tags: ["Ethereum", "Solana", "Fee Analysis", "Python", "Pandas"],
    category: "python",
  },
  {
    title: "Oracle Price Feed Analysis",
    description: "Analysis of oracle price feeds accuracy and reliability across different blockchain networks.",
    image: "/oracle-price-feed.png",
    link: "https://www.kaggle.com/code/omojoallwell/oracle-price-feed-analysis",
    tags: ["Oracles", "Price Feeds", "Data Reliability", "Python", "Time Series"],
    category: "python",
  },
  {
    title: "ETH DEX Performance Comparison",
    description: "Comparative analysis of performance metrics for major decentralized exchanges on Ethereum.",
    image: "/eth-dex-comparison.png",
    link: "https://www.kaggle.com/code/omojoallwell/comparison-of-eth-dex-performance",
    tags: ["DEX", "Ethereum", "Performance Analysis", "Python", "Matplotlib"],
    category: "python",
  },
  {
    title: "ERC20 Transfers Analysis",
    description: "In-depth analysis of ERC20 token transfer patterns and user behaviors on Ethereum.",
    image: "/erc20-transfers.png",
    link: "https://www.kaggle.com/code/omojoallwell/assignment-on-erc20",
    tags: ["ERC20", "Token Transfers", "User Behavior", "Python", "NetworkX"],
    category: "python",
  },
  {
    title: "Top Sell Volume on Solana",
    description: "Analysis of top selling patterns and volume distribution on the Solana blockchain.",
    image: "/solana-sell-volume.png",
    link: "https://www.kaggle.com/code/omojoallwell/top-sell-volume-on-sol-23-12-24",
    tags: ["Solana", "Trading Volume", "Market Analysis", "Python", "Seaborn"],
    category: "python",
  },
]

// Personal Projects
export const personalProjects = [
  {
    title: "Coresightbot",
    description:
      "A DeFi trading research bot that identifies the most profitable on-chain traders on Solana and EVM chains. The bot analyzes trading patterns, success rates, and profitability metrics to help users discover successful trading strategies.",
    image: "/coresight-logo.jpg",
    link: "https://t.me/coresight_bot",
    tags: ["DeFi", "Trading Research", "Telegram Bot", "Multi-chain", "On-chain Analysis"],
    category: "personal",
  },
  {
    title: "sc0pe",
    description:
      "A cross-chain analytics platform built on the 0G tech stack, providing comprehensive blockchain data analysis and insights across multiple networks. Features real-time analytics, cross-chain data aggregation, and advanced visualization tools for DeFi and blockchain research.",
    image: "/sc0pe-cover.jpg",
    link: "https://sc0pe.xyz",
    tags: ["Cross-chain Analytics", "0G Tech Stack", "DeFi Analytics", "Multi-chain", "Data Visualization"],
    category: "personal",
  },
]
